### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by blinskey** [blinskey/greek-reference#118]
It would be nice to add Google Analytics so we could track crashes and usage. We should either make data reporting opt-in or display a prominent opt-out notice the first time the app is run.

**Comment by IzzySoft** [comment]
Or maybe rather chose something less intrusive to the users' privacy :innocent: There are alternatives. Not sure which one's are best suited, as I'm no dev …

**Comment by blinskey** [comment]
Hi there! Thanks for your comments. I think my original goal here was to gather more crash reports, but I've actually stopped development on this app, so I'll go ahead and close this issue.

**Comment by IzzySoft** [comment]
It's a pity to read you've stopped on it :anguished: Until you (hopefully/maybe) pick it up again, maybe it would be a good idea to put a note on the "frontpage" (i.e. the main `README.md`) stating the project is (currently) unmaintained?

**Comment by blinskey** [comment]
There's a note to that effect in the Status section of the readme.

**Comment by IzzySoft** [comment]
Ah – sorry, must have missed that. Thanks!
