### ISSUE TITLE
Make search scroll to the nearest match

### ISSUE THREAD

**Issue by geowy** [blinskey/greek-reference#126]
It would be nice if the app automatically scrolled to the nearest match in the word list as you entered a search term. It's kind of painful to scroll through the word list manually because it's so long, but this would make navigating the it a lot easier. If you did it this way you could probably retire the search drop-down as well.

**Comment by blinskey** [comment]
Thanks for the suggestion! It would definitely be nice to make navigating the lexicon easier.
