### ISSUE TITLE
Publish APK at Github?

### ISSUE THREAD

**Issue by IzzySoft** [blinskey/greek-reference#158]
Would you consider publishing the `.apk` here at Github (preferably attaching them to their resp. `releases/`), so folks w/o Playstore could use the app? I'd then offer adding it to [my F-Droid compatible repo](https://android.izzysoft.de/repo) and have it automatically updated there whenever a new release happens, so those folks would even get update notifications and could perform updates without much trouble :innocent:

**Comment by blinskey** [comment]
Thanks for your interest in the app! I've published the APK for the latest release, v1.10.0, on the [releases page](https://github.com/blinskey/greek-reference/releases/tag/v1.10.0).

**Comment by IzzySoft** [comment]
Thanks a lot, Ben! As promised, find it [here](https://apt.izzysoft.de/fdroid/index/apk/com.benlinskey.greekreference) (and [here](https://android.izzysoft.de/applists/category/named/reading_translate#group_307)). A pity you've stopped development of this! If at any time you pick it up again and publish a new `.apk` (attached to the resp. `releases/` tag), it should appear in my repo within ~24h automatically now.

**Comment by IzzySoft** [comment]
@blinskey as you've picked up development again :partying_face: may I ask for the APKs once more?

**Comment by blinskey** [comment]
Done!

**Comment by IzzySoft** [comment]
Thanks! WONDERFUL!

![image](https://github.com/blinskey/greek-reference/assets/6781438/95d5d87f-a72a-4b78-90cc-7d0b3eca2251)

If you want to get rid of that `DEPENDENCY_INFO_BLOCK`, that's easy:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by blinskey** [comment]
Thanks for the info. I'll keep that in mind if I release a new version in the future.
